# Generated by Django 3.1.4 on 2020-12-26 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
